on: [push]

jobs:
  parameterizable_docker_action_test_job:
    strategy:
      matrix:
        os-version: ['3.9.5']
    runs-on: ubuntu-latest
    name: A job to create parameterizable docker action
    steps:
    # To use this repository's private action, you must check out the repository
    - name: Checkout to root dir
      uses: actions/checkout@v2
    - name: Create alpine image with parameterizable version
      id: alpine
      uses: ./
      with:
        branch-to-test: 'master'
        ao-token-prod: 'some-special-secret'
        alpine-version: ${{matrix.os-version}}
    # Use the output from the `alpine` step
    - name: show all arguments from first script
      run: echo "all arguments ${{steps.alpine.outputs.all-args}}"
    - name: all arguments from second script
      run: echo "all args 2 ${{steps.alpine.outputs.all-args-2}}"
    - name: Get alpine version
      run: echo "alpine ${{steps.alpine.outputs.version}}, branch ${{steps.alpine.outputs.branch-to-test}}"
