on: [push]

jobs:
  parameterizable_docker_action_test_job:
    strategy:
      matrix:
        os-version: ['3.9.5']
    runs-on: ubuntu-latest
    name: A job to create parameterizable docker action
    steps:
    # To use this repository's private action, you must check out the repository
    - name: Checkout to root dir
      uses: actions/checkout@v2
    - name: Create alpine image with parameterizable version
      id: alpine
      uses: ./
      with:
        alpine-version: ${{matrix.os-version}}
    # Use the output from the `alpine` step
    - name: Get alpine version
      run: echo "Alpine version is ${{ steps.alpine.outputs.version }}"
